config/routes.rb
Gfjohnson::Application.routes.draw do
	resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :lessons, only: [:new, :create, :destroy]
  resources :lesson_types, only: [:new, :create, :destroy]
  resources :private_lesson_package_types, only: [:new, :create, :index, :destroy]
  resources :website_settings, only: [:index, :edit, :update]

	root to: "static_pages#home"
	
	match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

	match "/products_and_services", to: "static_pages#products_and_services"
	match "/technology", to: "static_pages#technology"
	match "/about", to: "static_pages#about"
	match "/contact", to: "static_pages#contact"

	

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
    #@lesson = current_user.lessons.build if signed_in?    
    if signed_in?
      if current_user.admin?
        @lessons = Lesson.paginate(page: params[:page])
      else
        @lessons = current_user.lessons.paginate(page: params[:page]) if signed_in?
      end
    end
	end
	
	def products_and_services
    @private_lesson_package_types = PrivateLessonPackageType.where("is_active = true")
	end
	
	def technology
	end
	
	def about
	end
	
	def contact
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in_home.html.erb
<div class="row-fluid">
  <aside class="span4">
    <section>
      <%= render "shared/user_info" %>      
    </section>
    <% if !current_user.admin? %>
      <section>
        <%= link_to "Schedule a lesson", new_lesson_path, class: "btn btn-success" %>
        <% # render "shared/lesson_form" %>
      </section>
    <% end %>
  </aside>
  <div class="span8">
    <%= render "shared/lessons" %>
  </div>
</div>

app/views/static_pages/_normal_home.html.erb
<div class="row-fluid">
  <div class="center hero-unit">
    <h1>Welcome to <span style="white-space: nowrap;">G. F.</span> Johnson Golf</h1>
    
    <h2>
      Helping you improve your game.
    </h2>
    
    <%= link_to "Schedule a lesson today!", new_lesson_path, class: "btn btn-large btn-primary" %>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <div id="myCarousel" class="carousel slide">
      <!-- <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class></li>
        <li data-target="#myCarousel" data-slide-to="2" class></li>
      </ol> -->
      <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag("Watermark/1200/20130328_golf-2.jpg", alt: "George sandtrap", class: "img-rounded") %>
        </div>
        <div class="item">
          <%= image_tag("Watermark/1200/20130328_golf-56.jpg", alt: "George mid-swing", class: "img-rounded") %>
        </div>
        <div class="item">
          <%= image_tag("Watermark/1200/20130328_golf-22.jpg", alt: "George computer", class: "img-rounded") %>
        </div>
      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
    <script type="text/javascript"> 
        $('.carousel').carousel({ 
          interval: 5000,
          pause: "hover"
        }) 
    </script>
  </div>
</div>

<div class="row-fluid">
  <ul class="thumbnails">
    <li class="span4" style="min-width:250px;">
      <div class="thumbnail">
        <%= link_to image_tag("PGA.jpg", alt: "PGA", class: "img-rounded"), about_path %>
        <h3>PGA</h3>
        <p>
          Certified PGA Professional.
        </p>
        <%= link_to raw("About me &raquo;"), about_path, class: "btn" %>        
      </div>
    </li>
    <li class="span4" style="min-width:250px;">
      <div class="thumbnail">
        <%= link_to image_tag("TrackMan_logo.png", alt: "Trackman Golf", class: "img-rounded"), technology_path %>
        <h3>Trackman Pro</h3>
        <p>The world's most trusted launch monitor. Allows for instant recording of ball flight and club swing data.</p>
        <%= link_to raw("Learn more &raquo;"), technology_path , class: "btn" %>
      </div>
    </li>
    <li class="span4" style="min-width:250px;">
      <div class="thumbnail">
        <%= link_to image_tag("Zenio.png", alt: "Zenio Sports", class: "img-rounded"), technology_path %>
        <h3>Zenio</h3>
        <p>ZENIO is a revolutionary new training and fitting system that 
        gives golfers immediate and accurate data on their putting in real 
        time and in real outdoor  conditions.
        </p>
        <%= link_to raw("Learn more &raquo;"), technology_path, class:"btn" %>
      </div>
    </li>
  </ul>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

<!-- PGA Professional -->
<div class="row-fluid">
  
  <div class="span4" style="min-width:250px">
    <%= image_tag("PGA.jpg", alt: "PGA", class: "img-rounded") %>
    <h2>Certified PGA Professional</h2>
  </div>  
  
  <div class="span8" style="min-width:250px">
    <h3>My Mission</h3>
    <p>
      Through golf lessons and clinics, I will assess what golf means 
      to an individual and develop goals and expectations that will 
      help each person experience the game of golf in a fun and exciting way.
    </p>
  </div>

</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<address>
	<strong>George F. Johnson</strong> <br/>
	<abbr title="Phone">P:</abbr> <a href="tel:+12259365335">(225) 936-5335</a> <br/>
	<abbr title="Email">E:</abbr> <a href="mailto:georgejohnson85@gmail.com">georgejohnson85@gmail.com</a> <br/>
</address>

<address>
	<strong>Santa Maria Golf Academy</strong><br/>
	18460 Santa Maria Pkwy <br/>
	<abbr title="Phone">P:</abbr> <a href="tel:+12257533082">(225) 753-3082</a> <br/>
</address>

<address>
	<strong>Santa Maria Golf ProShop</strong> <br/>
	<abbr title="Phone">P:</abbr> <a href="tel:+12257529667">(225) 752-9667</a> <br/>
	Course Manager: <a href="mailto:bkernan@brec.org">Boyd Kernan</a> <br/>	
</address>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <%= render "logged_in_home" %>
<% else %>
  <%= render "normal_home" %>
<% end %>

app/views/static_pages/products_and_services.html.erb
<% provide(:title, "Products and Services") %>
<h1>Products & Services</h1>
<div class="row-fluid">	
	<div class="span6" style="min-width: 300px;">
		<table class="table table-striped table-bordered table-hover">
			<caption><h3>Private Lessons</h3></caption>
			<thead>
				<tr>
					<th></th>
					<th>Duration</th>
					<th>Cost ($)</th>
				</tr>
			</thead>
      <tbody>
        <% for private_lesson_package_type in @private_lesson_package_types %>
				  <tr>
            <td><%= private_lesson_package_type.name %></td>
            <td><%= private_lesson_package_type.duration_in_minutes %></td>
            <td><%= private_lesson_package_type.cost_in_dollars %></td>
				  </tr>
        <% end %>
			</tbody>
		</table>
    <% if signed_in? and current_user_is_admin? %>
      <%= link_to "Edit", private_lesson_package_types_path, title: "Edit private lesson package types", class: "btn btn-success" %>
    <% end %>
	</div>
	<div class="span6" style="min-width: 300px;">
		<table class="table table-striped table-bordered table-hover">
			<caption><h3>Coaching Programs *</h3></caption>
			<thead>
				<tr>
					<th></th>
					<th>Duration</th>
					<th>Cost ($)</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Twice a month</td>
					<td>45 mins</td>
					<td>480</td>
				</tr>
				<tr>
					<td>Weekly</td>
					<td>45 mins</td>
					<td>840</td>
				</tr>
				<tr>
					<td>Twice a week</td>
					<td>45 mins</td>
					<td>1440</td>
				</tr>
			</tbody>
		</table>
		<p>* Coaching Programs have a duration of 3 months. Also includes access to the practice tee for one hour per week.</p>
	</div>
</div>
<div class="row-fluid">
	<div class="span6" style="min-width: 300px;">
		<table class="table table-striped table-bordered table-hover">
			<caption><h3>Golf Classes</h3></caption>
			<thead>
				<tr>
					<th></th>
					<th>Duration</th>
					<th>Cost ($)</th>
					<th>Schedule</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>SNAG 1.0</td>
					<td>45 mins</td>
					<td>20</td>
					<td>TBA</td>
				</tr>
				<tr>
					<td>SNAG 2.0</td>
					<td>45 mins</td>
					<td>20</td>
					<td>TBA</td>
				</tr>
				<tr>
					<td>Full Swing Clinic</td>
					<td>45 mins</td>
					<td>20</td>
					<td>TBA</td>
				</tr>
				<tr>
					<td>Short Game Clinic</td>
					<td>45 mins</td>
					<td>20</td>
					<td>TBA</td>
				</tr>
				<tr>
					<td>Get Golf Ready</td>
					<td>5 60 min sessions</td>
					<td>100</td>
					<td>TBA</td>
				</tr>		
			</tbody>
		</table>
	</div>
	<div class="span6" style="min-width: 300px;">
		<table class="table table-striped table-bordered table-hover">
			<caption><h3>Corporate Packages</h3></caption>
			<thead>
				<tr>
					<th></th>
					<th>Duration</th>
					<th>Cost ($)</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Clinics</td>
					<td>45 mins</td>
					<td>100 (Up to 6 people)</td>
				</tr>
				<tr>
					<td>Golf School</td>
					<td>6 hours</td>
					<td>350 (Up to 6 people)</td>
				</tr>
				<tr>
					<td>Private 1-on-1 Lesson</td>
					<td>45 mins</td>
					<td>85</td>
				</tr>		
			</tbody>
		</table>
	</div>
</div>

app/views/static_pages/technology.html.erb
<% provide(:title, "Technology") %>

<h1>Technology</h1>

<!-- Trackman -->
<hr/>
<h2>Trackman Pro</h2>
<div class="row-fluid">
  <div class="span4 offset2">
    <section>
      <p>
        TrackMan Pro is the choice of the PGA Tour and R&A 
        for swing and ball flight analysis. A staple on professional 
        tours, with leading educators, club fitters, manufacturers 
        and players, TrackMan Pro is the industry standard for 
        accuracy, reliability and ease of use.
      </p>  
    </section>
  </div>  
  <div class="span4">
    <%= link_to image_tag("TM-Shortgame.jpg", alt: "Trackman Golf", class: "img-rounded"), asset_path("TM-Shortgame.jpg"), rel: "shadowbox" %>
  </div>  
</div>
<div class="row-fluid">
  <div class="span4 offset2">
    <section>
      <p>
        TrackMan Pro measures and displays the full trajectory of any shot, from 6-foot pitches to 400-yard drives, 
        pinpointing the landing position with an accuracy of 1 
        foot at 100 yards. Delivering state-of-the-art data without 
        using any modeling, TrackMan Pro displays the shot's 
        actual 3D trajectory in real time together with all impact 
        and ball flight information.
      <p>
    </section>
  </div>
  <div class="span4">
    <%= link_to image_tag("Live-JustinRose.jpg", alt: "Justin Rose Live", class: "img-rounded"), asset_path("Live-JustinRose.jpg"), rel: "shadowbox" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span8 offset2">
    <div>
      <%= video_tag(["assets/TrackMan-Branding-video.mp4", "assets/TrackMan-Branding-video.ogg", "assets/TrackMan-Branding-video.webm"], alt: "TrackMan Branding Video", controls: true, class:"video", poster: "TrackMan Video Image.png") %>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span4 offset4">
    <div class="center foreign-link">
      <%= link_to raw("Go to Trackman's website &raquo;"), "http://trackman.dk/Products/TrackMan-Pro.aspx", target: "_blank", class:"btn btn-large btn-success" %>
    </div>
  </div>
</div>

<!-- Zenio -->
<hr/>
<h2>Zenio Putting System</h2>
<div class="row-fluid">
  <div class="span4 offset2">
    <p>
      ZENIO is a revolutionary new training and fitting system that gives golfers immediate and accurate data on their putting in real time and in real outdoor conditions. Measuring the size of a matchbox and weighing just 29 grams, the ZENIO attaches to any putter in just 15 seconds. It uses the latest sensor technology to measure the key parameters of the putting stroke - impact, rhythm and face angle - and then immediately transmits the information to a Smartphone of PDA via Bluetooth, where it is displayed in an easy-to-understand graphical format.
    </p>
  </div>
  <div class="span4">
    <%= link_to image_tag("Face_sensor3.jpg", alt: "Face sensor", class: "img-rounded"), asset_path("Face_sensor3.jpg"), rel: "shadowbox" %>    
  </div>
</div>
<div class="row-fluid">
  <div class="span4 offset2">
    <p>
      With data from each session being recorded, users can chart their progress over time on all manner of putts (straight, breaking, uphill, downhill) from a variety of different distances, helping to build up a clear picture of putting strengths and weaknesses and how to improve your putting consistency . ZENIO's innovative software uses the player's "Best" performance as a benchmark for future sessions and also includes a Tour player consistency benchmark for comparison. Golfers can also use the ZENIO to find their optimum stance, grip and posture, and by using the fitting option can even reveal which putter type suits their stroke best.
    </p>
  </div>
  <div class="span4">
    <%= link_to image_tag("training-compare-sess2.jpg", alt: "Training sessions results", class: "img-rounded"), asset_path("training-compare-sess2.jpg"), rel: "shadowbox" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4 offset4">
    <div class="center foreign-link">
      <%= link_to raw("Go to Zenio's website &raquo;"), "http://www.zeniogolf.com/", target: "_blank", class: "btn btn-large btn-success"%>
    </div>
  </div>
</div>