config/routes.rb
Gfjohnson::Application.routes.draw do
	resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :lessons, only: [:new, :create, :destroy]
  resources :lesson_types, only: [:new, :create, :destroy]
  resources :private_lesson_package_types, only: [:new, :create, :index, :destroy]
  resources :website_settings, only: [:index, :edit, :update]

	root to: "static_pages#home"
	
	match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

	match "/products_and_services", to: "static_pages#products_and_services"
	match "/technology", to: "static_pages#technology"
	match "/about", to: "static_pages#about"
	match "/contact", to: "static_pages#contact"

	

end

app/controllers/private_lesson_package_types_controller.rb
class PrivateLessonPackageTypesController < ApplicationController
  before_filter :signed_in_user
  before_filter :admin_user

  def index
    @private_lesson_package_types = PrivateLessonPackageType.where("is_active = true").paginate(page: params[:page])
  end

  def show
  end

  def new
    @private_lesson_package_type = PrivateLessonPackageType.new
  end

  def create
    @private_lesson_package_type = PrivateLessonPackageType.new(params[:private_lesson_package_type])
    if (@private_lesson_package_type.save)
      flash[:success] = "Private lesson package type added!"
      redirect_to private_lesson_package_types_url
    else
      render "new"
    end
  end

  def destroy
    @private_lesson_package_type = PrivateLessonPackageType.find(params[:id])
    @private_lesson_package_type.toggle!(:is_active)
    flash[:success] = "Private lesson package type deactivated"
    redirect_to private_lesson_package_types_url
  end
end

app/views/private_lesson_package_types/_private_lesson_package_type.html.erb
<tr>
  <td><%= private_lesson_package_type.name %></td>
  <td><%= private_lesson_package_type.duration_in_minutes %></td>
  <td><%= private_lesson_package_type.cost_in_dollars %></td>
  <td>
    <%= link_to "delete", private_lesson_package_type, method: :delete,
      data: {confirm: "Are you sure?" }, title: "Deactivate private lesson package type" %>
  </td>
</tr>

app/views/private_lesson_package_types/index.html.erb
<%= provide(:title, "All private lesson package types") %>
<h1>All private lesson package types</h1>

<div class="row-fluid">
  <div class="span6 offset3" style="min-width: 300px;">
    <%= will_paginate %>

    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Duration</th>
          <th>Cost ($)</th>
          <th></th>
        </tr>
      </thead>
      <%= render @private_lesson_package_types %>
    </table>

    <%= will_paginate %>

    <%= link_to "Add new private lesson package type", new_private_lesson_package_type_path, class: "btn btn-success" %>
  </div>
</div>

app/views/private_lesson_package_types/new.html.erb
<%= provide(:title, "New private lesson package type") %>
<h1> New Private Lesson Package Type</h1>

<div class="row-fluid">
  <aside class="span6 offset3" style="min-width: 200px;">
    <%= form_for(@private_lesson_package_type) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :duration_in_minutes %>
      <%= f.number_field :duration_in_minutes, min: 0 %>

      <%= f.label :cost_in_dollars %>
      <%= f.number_field :cost_in_dollars, min: 0 %>

      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </aside>
</div>