config/routes.rb
Gfjohnson::Application.routes.draw do
	resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :lessons, only: [:new, :create, :destroy]
  resources :lesson_types, only: [:new, :create, :destroy]
  resources :private_lesson_package_types, only: [:new, :create, :index, :destroy]
  resources :website_settings, only: [:index, :edit, :update]

	root to: "static_pages#home"
	
	match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

	match "/products_and_services", to: "static_pages#products_and_services"
	match "/technology", to: "static_pages#technology"
	match "/about", to: "static_pages#about"
	match "/contact", to: "static_pages#contact"

	

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		&copy; G. F. Johnson Golf 2013 | 
		Created by <a href="http://thegradientvector.com" target="_blank">John Harvey</a>
	</small>
	<!-- &middot; -->
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li>|</li>
			<li><%= link_to "Back to top", "#" %></li>
		</ul>
	</nav>
  <span id="site-seal"> 
    <script type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=ZiaYxUseYgMYmfDnfTmuLRu0xzLMgNXoGHUtpKCnfaHfozz60p1smRVdVuGP">
    </script>
  </span>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="logo" class="brand" href="<%= root_path %>">
        <%= image_tag("logo4.png", alt: "G. F. Johnson Golf") %> 
        <span class="logo-text">Golf</span>
      </a>
      <nav class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Products & Services", products_and_services_path %></li>
          <li><%= link_to "Technology", technology_path %></li>
          <% if signed_in? %>
            <% if current_user_is_admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% if current_user_is_admin? %>
                  <li><%= link_to "Website Settings", website_settings_path %></li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
      <!--/.nav-collapse -->
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render "layouts/shim" %>
    <script type="text/javascript">
      Shadowbox.init();
    </script>
  </head>

  <body>
    <!-- Header -->
    <%= render "layouts/header" %>
    
    <div class="container-fluid">      
      <!-- Alert messages -->
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= value %>
        </div>
      <% end %>
      
      <!-- Page content -->
      <%= yield %>
      
      <!-- Footer -->
      <%= render "layouts/footer" %>
      
      <!-- Debug information during development -->
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>